security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        db_provider:
            entity:
              class: App\Entity\User
              property: email
      
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: db_provider

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
